name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    name: ${{ matrix.python }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python: "3.10"
          - os: ubuntu-latest
            python: "3.11"
          - os: ubuntu-latest
            python: "3.12"
          - os: ubuntu-latest
            python: "3.13"
          - os: windows-latest
            python: "3.13"
          - os: macos-latest
            python: "3.13"
          - os: ubuntu-latest
            python: "pypy3.10"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install pylivemaker
        run: |
          pip install --constraint=.github/workflows/constraints.txt .[test]

      - name: Run tests
        run: |
          pytest --cov=livemaker --cov-report=xml --cov-report=term

      - name: Upload coverage data
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
